FishAndPlaces\Dam\Domain\Model\DamImage:
    repositoryClass: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineDamImageRepository
    type: entity
    table: dam_image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        imageSrc:
            type: string
            column: image_src
        isMain:
            type: boolean
            column: is_main
    manyToOne:
        dam:
            targetEntity: FishAndPlaces\Dam\Domain\Model\Dam
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: null
            inversedBy: imageCollection
            joinColumns:
                dam_id:
                    referencedColumnName: id
                    onDelete: null
            orphanRemoval: false
    lifecycleCallbacks: {  }
