FishAndPlaces\Dam\Domain\Model\FishImage:
    repositoryClass: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineFishImageRepository
    type: entity
    table: fish_image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        imageSrc:
            type: string

    manyToOne:
        image:
            targetEntity: FishAndPlaces\Dam\Domain\Model\Fish
            inversedBy: fishImages
            joinColumn:
                name: fish_id
                referencedColumnName: id
