services:
    fish_and_places.dam_repository:
        class: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineDamRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\Dam\Domain\Model\Dam ]

    fish_and_places.fish_repository:
        class: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineFishRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\Dam\Domain\Model\Fish ]

    fish_and_places.dam_image_repository:
        class: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineDamImageRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\Dam\Domain\Model\DamImage ]

    fish_and_places.fish_image_repository:
        class: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineFishImageRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\Dam\Domain\Model\FishImage ]

    fish_and_places.local_geocoder_repository:
        class: FishAndPlaces\Dam\Infrastructure\Repository\Doctrine\ORM\DoctrineGeocoderLocalRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\Dam\Domain\Model\Geocoder ]

    fish_and_places.geocoder_proxy:
        class:  FishAndPlaces\Dam\Infrastructure\Geocoder\GeocoderProxy

    fish_and_places.geolocator:
        class: FishAndPlaces\Dam\Application\Dam\GeoLocatorService
        arguments:
            - "@fish_and_places.geocoder_proxy"
            - "@fish_and_places.local_geocoder_repository"

    fish_and_places.dam_query_service:
        class: FishAndPlaces\Dam\Application\Dam\DamQueryService
        arguments:
            - "@fish_and_places.dam_repository"
            - "@fish_and_places.geolocator"

    fish_and_places.fish_query_service:
        class: FishAndPlaces\Dam\Application\Fish\FishQueryService
        arguments:
            - "@fish_and_places.fish_repository"

    fish_and_places.dam_service:
        class: FishAndPlaces\Dam\Application\Dam\DamService
        arguments:
            - "@fish_and_places.dam_repository"
            - "@fish_and_places.geolocator"

    fish_and_places.fish_service:
        class: FishAndPlaces\Dam\Applicaiton\Fish\FishService
        arguments:
            - "@fish_and_places.fish_repository"
