imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DamBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    images_upload: '%kernel.root_dir%/../web/uploads/images'

framework:
    #esi:             ~
    translator:      { fallbacks: ["bg"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    user:
                        type:      yml
                        dir:       %kernel.root_dir%/../src/FishAndPlaces/User/Infrastructure/Mapping/ORM
                        prefix:    FishAndPlaces\User\Domain\Model
                        alias:     DamBundle
                        is_bundle: false

                    shop:
                        type:      yml
                        dir:       %kernel.root_dir%/../src/FishAndPlaces/Shop/Infrastructure/Mapping/ORM
                        prefix:    FishAndPlaces\Shop\Domain\Model
                        alias:     ShopBundle
                        is_bundle: false
                    dam:
                        type:      yml
                        dir:       %kernel.root_dir%/../src/FishAndPlaces/Dam/Infrastructure/Mapping/ORM
                        prefix:    FishAndPlaces\Dam\Domain\Model
                        alias:     DamBundle
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: FishAndPlaces\User\Domain\Model\User
    from_email:
        address: vesela.ferdinandova@gmail.com
        sender_name: Vesela
services:
    fos_user.doctrine_registry:
        alias: doctrine
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
ivory_google_map:
    map:
        debug: "%kernel.debug%"
        language: "%locale%"
        api_key: "%google_maps_api_key%"
sensio_framework_extra:
    router:      { annotations: true }
    request:     { converters: true, auto_convert: true }
    view:        { annotations: true }
    cache:       { annotations: true }
    security:    { annotations: true }
    psr_message: { enabled: false }
#kms_froala_editor:
#  language: "en_gb"
#  toolbarInline: false
#  tableColors: [ "#FFFFFF", "#FF0000" ]
#  saveParams: { "id" : "description" }
#  pluginsEnabled: [ "image", "file" ]
#  includeJQuery: true
#
#  # Disable CodeMirror inclusion.
#  includeCodeMirror: true
#
#   # Disable Font Awesome inclusion.
#  includeFontAwesome: true
#
#  # Disable all bundle javascripts inclusion (not concerning JQuery nor CodeMirror).
#  # Usage: if you are using Grunt or other and you want to include yourself all scripts.
#  includeJS: true
#
#  # Disable all bundle CSS inclusion (not concerning Font Awesome nor CodeMirror).
#  # Usage: if you are using Grunt or other and you want to include yourself all stylesheets.
#  includeCSS: true
#  imageUploadFolder: "/uploads/user"
#
#  # The image upload URL base.
#  # Usage: if you are using URL rewritting for your assets.
#  # Default: same value as provided as folder.
#  imageUploadPath: "%kernel.root_dir%/../web/uploads/user"

ivory_ck_editor:
    enable: true
    jquery: false
    input_sync: true
    configs:
        my_config:
            toolbar: "full"
            extraPlugins: "uploadimage"
            imageUploadUrl: "uploader/upload.php?type=Images"
    toolbars:
        items:
            full.colors: [ "TextColor", "BGColor" ]
            full.document: [ "Source", "-", "Preview", "Print" ]
