dam:
    resource: "@DamBundle/Controller/"
    type:     annotation
shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
   path: /logout
