go_green:
    resource: "@GoGreenBundle/Controller/"
    type:     annotation
    prefix: /
shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
api:
    resource: "@APIBundle/Controller/"
    type:     annotation
    prefix:   /api/v1/
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
