# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    credissimo.user_repository:
        class: FishAndPlaces\User\Infrastructure\Repository\Doctrine\ORM\DoctrineUserRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\User\Domain\Model\User ]
