FishAndPlaces\GreenObject\Domain\Model\Fish:
    type: entity
    table: fish
    repositoryClass: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineFishRepository
    id:
        id:
            id: true
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        name:
            type: string
            length: '255'
        image:
            type: string
            length: '40'
        description:
            type: string
        isActive:
            type: boolean
            column: is_active
    lifecycleCallbacks: {  }
