FishAndPlaces\GreenObject\Domain\Model\Geocoder:
    repositoryClass: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineGeocoderLocalRepository
    type: entity
    table: geocoder
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        address:
            type: string
        longitude:
            type: float
        latitude:
            type: float
