services:
    fish_and_places.cabin_repository:
        class: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineCabinRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\GreenObject\Domain\Model\Cabin ]

    fish_and_places.cabin_query_service:
        class: FishAndPlaces\GreenObject\Application\GreenObject\Camp\CampQueryService
        arguments:
            - "@fish_and_places.cabin_repository"
            - "@fish_and_places.geolocator"

    fish_and_places.cabin_service:
        class: FishAndPlaces\GreenObject\Application\GreenObject\Cabin\CabinService
        arguments:
            - "@fish_and_places.cabin_repository"
            - "@fish_and_places.geolocator"
            - "@fish_and_places.greenobject_image_repository"
