services:
    fish_and_places.dam_repository:
        class: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineDamRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\GreenObject\Domain\Model\Dam ]

    fish_and_places.fish_repository:
        class: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineFishRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\GreenObject\Domain\Model\Fish ]

    fish_and_places.dam_query_service:
        class: FishAndPlaces\GreenObject\Application\GreenObject\Dam\DamQueryService
        arguments:
            - "@fish_and_places.dam_repository"
            - "@fish_and_places.geolocator"

    fish_and_places.fish_query_service:
        class: FishAndPlaces\GreenObject\Application\Fish\FishQueryService
        arguments:
            - "@fish_and_places.fish_repository"

    fish_and_places.dam_service:
        class: FishAndPlaces\GreenObject\Application\GreenObject\Dam\DamService
        arguments:
            - "@fish_and_places.dam_repository"
            - "@fish_and_places.geolocator"
            - "@fish_and_places.greenobject_image_repository"
            - "@fish_and_places.fish_repository"

    fish_and_places.fish_service:
        class: FishAndPlaces\GreenObject\Application\Fish\FishService
        arguments:
            - "@fish_and_places.fish_repository"
