imports:
    - { resource: cabin.yml }
    - { resource: camp.yml }
    - { resource: dam.yml }
    - { resource: village_holiday.yml }

services:
    fish_and_places.greenobject_image_repository:
        class: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineGreenObjectImageRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\GreenObject\Domain\Model\GreenObjectImage ]

    fish_and_places.local_geocoder_repository:
        class: FishAndPlaces\GreenObject\Infrastructure\Repository\Doctrine\ORM\DoctrineGeocoderLocalRepository
        factory: ["@doctrine", getRepository]
        arguments: [ FishAndPlaces\GreenObject\Domain\Model\Geocoder ]

    fish_and_places.geocoder_proxy:
        class:  FishAndPlaces\GreenObject\Infrastructure\Geocoder\GeocoderProxy

    fish_and_places.geolocator:
        class: FishAndPlaces\GreenObject\Application\Core\GeoLocatorService
        arguments:
            - "@fish_and_places.geocoder_proxy"
            - "@fish_and_places.local_geocoder_repository"
